# Generated by Django 5.2 on 2025-04-25 14:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('place', models.CharField(max_length=3000)),
                ('archive', models.BooleanField(default=False)),
                ('type_game', models.IntegerField(choices=[(0, 'Смешанные'), (1, 'Баскетбол'), (2, 'Футбол'), (3, 'Хоккей'), (4, 'Теннис'), (5, 'Волейбол'), (6, 'Пинг-понг'), (7, 'Регби')], default=0)),
                ('count_player_now', models.IntegerField()),
                ('count_player_max', models.IntegerField()),
                ('now_rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.competition')),
            ],
        ),
    ]
