# Generated by Django 5.2 on 2025-04-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_competition_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='image',
            field=models.ImageField(default=0, upload_to='imgs/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competition',
            name='type_game',
            field=models.IntegerField(choices=[(0, 'Смешанные'), (1, 'Баскетбол'), (2, 'Футбол'), (3, 'Хоккей'), (4, 'Теннис'), (5, 'Волейбол'), (6, 'Пинг-понг'), (7, 'Регби'), (8, 'Киберспорт')], default=0),
        ),
    ]
