# Generated by Django 5.2 on 2025-04-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_competition_image_alter_competition_type_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='image',
            field=models.ImageField(upload_to='imgs'),
        ),
    ]
