# Generated by Django 5.2 on 2025-04-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='count1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='count2',
            field=models.IntegerField(default=0),
        ),
    ]
