# Generated by Django 5.2 on 2025-04-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_game_count1_game_count2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='archive',
            field=models.IntegerField(choices=[(0, 'Неактивно'), (1, 'Идёт набор'), (2, 'Набор закрыт')], default=1),
        ),
    ]
