# Generated by Django 5.2 on 2025-04-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_competition_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='command',
            field=models.BooleanField(default=1),
        ),
    ]
