# Generated by Django 5.2 on 2025-04-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_competition_creator_game_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='active',
            field=models.BooleanField(default=1),
        ),
    ]
