# Generated by Django 5.2 on 2025-04-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_template_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='command',
            field=models.BooleanField(default=1),
        ),
    ]
